version: "3"

x-uffizzi:
  ingress:
    service: web
    port: 8080

services:
    web:
        image: "${CONVOY_IMAGE}"
        entrypoint: ["/bin/sh"] 
        command: /uffizzi/start.sh
        ports:
        - 8080:8080
        environment:
        # - CONVOY_QUEUE_PROVIDER='redis'
        # - CONVOY_REDIS_DSN='redis://localhost:6379'
        # - CONVOY_DB_TYPE='mongo'
        # - CONVOY_DB_DSN='mongodb://127.0.0.1:27017,127.0.0.1:27019/convoy?replicaSet=localhost'
        - CONVOY_HOST='localhost'
        - PORT=8080
        # - CONVOY_REQUIRE_AUTH=false
        # - CONVOY_JWT_REALM_ENABLED=false
        # - CONVOY_NATIVE_REALM_ENABLED=false
        volumes:
            - ./uffizzi:/uffizzi:ro
            - ./uffizzi/convoy-uffizzi.json:/uffizzi/convoy.json
        deploy:
          resources:
            limits:
              memory: 4000M
    
    scheduler:
        image: "${CONVOY_IMAGE}"
        volumes:
            - ./uffizzi:/uffizzi:ro
        entrypoint: ["./cmd", "scheduler", "--config", "./uffizzi/convoy-uffizzi.json"]
        deploy:
          resources:
            limits:
              memory: 4000M

    worker:
        image: "${CONVOY_IMAGE}"
        volumes:
            - ./uffizzi:/uffizzi:ro
        entrypoint: ["./cmd", "worker", "--config", "./uffizzi/convoy-uffizzi.json"]
        deploy:
          resources:
            limits:
              memory: 4000M

    mongo:
      image: mongo:5.0.14
      entrypoint: ["/usr/bin/mongod", "--replSet", "localhost"]
      ports: 
        - "27017:27017"
        - "27018:27018"
        - "27019:27019"
      deploy:
          resources:
            limits:
              memory: 2000M  
   
    mongosetup:
        image: mongo:5.0.14
        entrypoint: [ "bash", "-c", "sleep 20 && mongo --host 127.0.0.1:27017 --eval 'rs.initiate()'"]    
        deploy:
          resources:
            limits:
              memory: 1000M   

    redis_server:
        image: redis:alpine

volumes:
  mongo1-data:
  mongo2-data: